server:
  port: 8080
security:
  user:
    password: user  # 直接登录时的密码
  ignored: /
  sessions: never   # session策略

  oauth2:
    sso:
      loginPath: /login   # 登录路径
    client:
      clientId: 5e5d6516c8e3263f8bdc      #github网站上注册生成的clientId
      clientSecret: 9b7bf6db82f9bca5f09cfcde60ce9617fa2659ea  #github网站上注册生成的secrity
      accessTokenUri: https://github.com/login/oauth/access_token
      userAuthorizationUri: https://github.com/login/oauth/authorize
    resource:
      userInfoUri: https://api.github.com/user
      preferTokenInfo: false
