
server:
  port: 8080
spring:
  profiles:
    active: test
---
server:
  port: 800
spring:
  profiles: dev
---
server:
  port: 8009
spring:
  profiles: test
---
server:
  port: 8008
spring:
  profiles: prod
