server:
  port: 8082
  tomcat:
    uri-encoding: utf-8
  context-path: /configDemo
spring:
  profiles:
    active: dev
  task:
    pool:
      corePoolSize: 1
      maxPoolSize: 5
      keepAliveSeconds: 1
      queueCapacity: 1
