spring:
  datasource:   #多数据源配置
    master:
      url: jdbc:mysql://localhost:3306/test3?useUnicode=true&characterEncoding=utf8&useSSL=false&pinGlobalTxToPhysicalConnection=true
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
    slave:
      url: jdbc:mysql://localhost:3306/test4?useUnicode=true&characterEncoding=utf8&useSSL=false&pinGlobalTxToPhysicalConnection=true
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
    #Hibernate ddl auto (validate|create|create-drop|update)
    #Hibernate ddl auto (validate|create|create-drop|update)
    hibernate:
      ddl-auto: create
#      naming:
#        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

#spring:
#  datasource:   #多数据源配置
#    type: com.alibaba.druid.pool.DruidDataSource
##    url: jdbc:mysql://localhost:3307/testdb?useUnicode=true&characterEncoding=utf8&useSSL=false
#    url: jdbc:mysql://localhost:3308/testdb?useUnicode=true&characterEncoding=utf8&useSSL=false
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.jdbc.Driver


#  jpa:
#    show-sql: true

#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.imooc.entity
#  configuration:
#    map-underscore-to-camel-case: true
#    cache-enabled: false
#    default-executor-type: reuse
#    default-statement-timeout: 600




